### ISSUE TITLE
Readme clarification

### ISSUE THREAD

**Issue by benmccann** [domingues/rollup-plugin-css-chunks#1]
The readme says "Use rollup-plugin-extract-bundle-tree to extract dependencies between JS and CSS chunks." Does that mean that you need to use `rollup-plugin-extract-bundle-tree` to use this plugin or is it optional?

I'm also wondering how the CSS gets included in the document. Is there something that updates the JS to include a `style` or `link` tag into the document or is it the user's responsibility to somehow load the CSS?

**Comment by benmccann** [comment]
Ah, I see that you have to use and extract the bundle tree in order to use this plugin: https://github.com/domingues/svelte-ssr-example/blob/2fe9ae73757b68056723f1c321c0a1d6053ff66f/src/server.js

**Comment by domingues** [comment]
Yes, you have to use something like that to know what are the chunks that your module use. At some point I tried to use `@import` CSS rule so it work with only one CSS style sheet `<link>`. But in production nobody will do that to avoid cascade file downloads.
