### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by antonlyap** [domingues/rollup-plugin-css-chunks#10]
Currently this package is hard to use in TypeScript apps because type definitions are neither included in it nor available as `@types/rollup-plugin-css-chunks` package in npm.
TypeScript definitions can be auto-generated using a `declaration: true` option in `tsconfig.json`. I can submit a PR with all the necessary stuff for this if you want.

**Comment by domingues** [comment]
The pull request is welcome, thank you.
