### ISSUE TITLE
2.0: url-join missing from dependencies

### ISSUE THREAD

**Issue by benmccann** [domingues/rollup-plugin-css-chunks#13]
I tried to use the new version, but got:

> Error: Cannot find module 'url-join'

I think `url-join` probably needs to be in `dependencies` instead of `devDependencies`

**Comment by domingues** [comment]
Should I move also `@types/url-join`?

**Comment by benmccann** [comment]
No, I don't think you need to because the `url-join` types are not being exported and will be completely erased at compile time
