### ISSUE TITLE
What does injectImports do?

### ISSUE THREAD

**Issue by benmccann** [domingues/rollup-plugin-css-chunks#18]
Whether I turn it on or off I don't see any difference, but I suspect I don't quite understand when it's being called or what it's doing.

Do you put an import statement in your JS and then it translates it to a CSS import statement? Does it prevent the CSS from being concatenated into a single CSS chunk that case? Will it act on all CSS modules in the chunk or only some?

**Comment by domingues** [comment]
It puts CSS [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) directives for each chunk it depends on.

**Comment by benmccann** [comment]
Thanks. I got it to trigger. I'm not quite sure what the difficulty I was having was. I'll raise a PR to expand the docs just slightly with your explanation
