### ISSUE TITLE
Deprecation warning when running

### ISSUE THREAD

**Issue by benmccann** [domingues/rollup-plugin-css-chunks#3]
When I run with the latest version of Rollup, I get the message:

> A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.

**Comment by domingues** [comment]
Didn't notice the rollup 2.0 update, let me check the changes than I will review your pull request. Thanks for notice.

**Comment by benmccann** [comment]
That's great! Thank you so much for the fix! :smile:
